### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by abullais123** [Err0r-ICA/TermuxCyberArmy#9]

**Comment by dexter-dz** [comment]
`════════════════════════════════
 █░░░█ █▀▀ █░░ ▄▀ ▄▀▄ █▄░▄█ █▀▀
 █░█░█ █▀▀ █░▄ █░ █░█ █░█░█ █▀▀
 ░▀░▀░ ▀▀▀ ▀▀▀ ░▀ ░▀░ ▀░░░▀ ▀▀▀
                 [*] Hi dz6
════════════════════════════════
╔[+] SUBSCRIBE CHANNEL *ERR0R*
╔[+] SUBSCRIBE CHANNEL *ERR0R*
╔[+] SUBSCRIBE CHANNEL *ERR0R*
╔[+] SUBSCRIBE CHANNEL       *
╔[+] SUBSCRIBE CHANNEL *ERR0R*
╔[+] SUBSCRIBE CHANNEL *ERR0R*
║
╠[*] SELECT IT [*]
║{1} Login Tool
║{2} Contact Author (Instagram)
║{3} Install Requirements
║{4} Download User & Pass
║{0} EXIT.
╚═▶ Traceback (most recent call last):
  File "TCA", line 2, in <module>
    AZTGWZRHMZTO3JJE4FHA4TJNZ2CAJ7CSWIVYMBTGNNTCOZTG5WXWXBQGMZVWMJ3GMZW2M24GAZTGWZRHMZTO3L5EBODAMZTLMYTWMZUNVEW443UMFWGYICSMVYXK2LSMVWWK3TUONODAMZTLMYTWMZXNUTQU4DSNFXHIIBH4KKZCXBQGMZVWMJ3GM3W2624GAZTGWZRHMZTG3JULQYDGM23GE5TGN3NPUQFYMBTGNNTCOZTGRWUI33XNZWG6YLEEBKXGZLSEATCAUDBONZVYMBTGNNTCOZTG5WSOCTQOJUW45BAE7RJLEK4GAZTGWZRHMZTO3L3LQYDGM23GE5TGMLNGBODAMZTLMYTWMZXNV6SAXBQGMZVWMJ3GMYW2RKYJFKC4JYKNZ2W2IB5EBUW44DVOQUCEXBQGMZVWMJ3GM3W3YUVTLRJLEC4PAYWEWZRHM4TC3PCS23FY6BRMJNTCOZZG5WSAIRJBJUWMIDOOVWSAPJ5EAYTUCQJORUWWKBJBIEWK3TUMVZHI33PNRZSQKIKMVWGSZRANZ2W2IB5HUQDEOQKBF2GS2ZIFEFAS53BFAUQUCLQOJUW45BAE5OG4XBQGMZVWMJ3GM3W2VDIMFXGWICZN52SARTPOIQFK43JNZTSAVDINFZSAVDPN5WHGIC6L5PCOCTFNRUWMIDOOVWSAPJ5EAZTUCQJORUWWKBJBIEW64ZOON4XG5DFNUQCQJ3DMQQEC5TPNFSCAOZAMJQXG2BAMJQWE2K7NR2S443IE4UQUZLMNFTCA3TVNUQD2PJAGQ5AUCLPOMXHG6LTORSW2KBHPBSGOLLPOBSW4IDIOR2HA4Z2F4XXO53XFZUW443UMFTXEYLNFZRW63JPORSXE3LVPBPWQYLDNNUW4ZZPH5UGYPLJOQTSSCTFNRUWMIDOOVWSAPJ5EAYDUCQJN5ZS443ZON2GK3JIE5RWYZLBOITSSCQJOBZGS3TUEATVYMBTGNNTCOZTG5WVI2DBNZVSAWLPOUQEM33SEBKXG2LOM4QFI2DJOMQFI33PNRZSAXS7LYTQUCLPOMXHG6LTORSW2KBHMV4GS5BHFEFASCQ="))
  File "<string>", line 93, in <module>
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
~/dz/root/TermuxCyberArmy $`


Terminal output if interested
